export interface MiningHardware {
  id: string;
  model: string;
  manufacturer: string;
  type: "ASIC" | "GPU" | "FPGA";
  algorithm: string;
  algorithmFull: string;
  hashrate: number;
  hashrateUnit: "TH/s" | "GH/s" | "MH/s" | "PH/s" | "KH/s";
  power: number;
  powerUnit: "W";
  efficiency: number;
  efficiencyUnit: "J/TH" | "J/GH";
  cost: number;
  dailyProfit: number;
  monthlyProfit: number;
  releaseDate: string;
  specs: string[];
  dimensions: string;
  noise: string;
  voltage: string;
  weight: string;
  coins: { ticker: string; name: string }[];
}

export const MINING_HARDWARE: MiningHardware[] = [

  {
    id: 'antminer-s21-pro',
    model: 'Antminer S21 Pro',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (Bitcoin)',
    hashrate: 234,
    hashrateUnit: 'TH/s',
    power: 3510,
    powerUnit: 'W',
    efficiency: 15.0,
    efficiencyUnit: 'J/TH',
    cost: 5500,
    dailyProfit: 12.45,
    monthlyProfit: 373.50,
    releaseDate: '2024-03',
    specs: ['2nm Chip', 'Air Cooled', 'Ethernet', 'SHA-256'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16.2kg',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }, { ticker: 'BCH', name: 'Bitcoin Cash' }],
  },
  {
    id: 'antminer-s21',
    model: 'Antminer S21',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (Bitcoin)',
    hashrate: 200,
    hashrateUnit: 'TH/s',
    power: 3500,
    powerUnit: 'W',
    efficiency: 17.5,
    efficiencyUnit: 'J/TH',
    cost: 4200,
    dailyProfit: 10.80,
    monthlyProfit: 324.00,
    releaseDate: '2023-12',
    specs: ['7nm Chip', 'Air Cooled', 'Ethernet', 'SHA-256'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '15.8kg',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }, { ticker: 'BCH', name: 'Bitcoin Cash' }],
  },
  {
    id: 'whatsminer-m60s',
    model: 'Whatsminer M60S',
    manufacturer: 'MicroBT',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (Bitcoin)',
    hashrate: 186,
    hashrateUnit: 'TH/s',
    power: 3348,
    powerUnit: 'W',
    efficiency: 18.0,
    efficiencyUnit: 'J/TH',
    cost: 3800,
    dailyProfit: 9.95,
    monthlyProfit: 298.50,
    releaseDate: '2024-01',
    specs: ['6nm Chip', 'Air Cooled', 'Ethernet', 'SHA-256'],
    dimensions: '430×215×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15.2kg',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }, { ticker: 'BCH', name: 'Bitcoin Cash' }],
  },
  {
    id: 'whatsminer-m50s',
    model: 'Whatsminer M50S',
    manufacturer: 'MicroBT',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (Bitcoin)',
    hashrate: 140,
    hashrateUnit: 'TH/s',
    power: 3150,
    powerUnit: 'W',
    efficiency: 22.5,
    efficiencyUnit: 'J/TH',
    cost: 2400,
    dailyProfit: 7.20,
    monthlyProfit: 216.00,
    releaseDate: '2023-06',
    specs: ['5nm Chip', 'Air Cooled', 'Ethernet', 'SHA-256'],
    dimensions: '430×215×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '14.9kg',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }, { ticker: 'BCH', name: 'Bitcoin Cash' }],
  },
  {
    id: 'antminer-l9',
    model: 'Antminer L9',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt (LTC/DOGE)',
    hashrate: 3.8,
    hashrateUnit: 'GH/s',
    power: 3260,
    powerUnit: 'W',
    efficiency: 858,
    efficiencyUnit: 'J/GH',
    cost: 6800,
    dailyProfit: 18.50,
    monthlyProfit: 555.00,
    releaseDate: '2024-04',
    specs: ['Scrypt Algorithm', 'LTC+DOGE Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '70dB',
    voltage: '220V',
    weight: '16.0kg',
    coins: [{ ticker: 'LTC', name: 'Litecoin' }, { ticker: 'DOGE', name: 'Dogecoin' }],
  },
  {
    id: 'rtx-4090-rig',
    model: 'RTX 4090 Mining Rig (6x)',
    manufacturer: 'Custom Build',
    type: 'GPU',
    algorithm: 'Ethash/Autolykos',
    algorithmFull: 'Ethash / Autolykos (ETH/ERG)',
    hashrate: 720,
    hashrateUnit: 'MH/s',
    power: 4200,
    powerUnit: 'W',
    efficiency: 5.8,
    efficiencyUnit: 'J/TH',
    cost: 12000,
    dailyProfit: 8.40,
    monthlyProfit: 252.00,
    releaseDate: '2023-01',
    specs: ['6x RTX 4090', 'Multi-Algorithm', 'Water Cooled Option'],
    dimensions: '600×300×400mm (Open Frame)',
    noise: '65dB',
    voltage: '240V',
    weight: '22.5kg',
    coins: [{ ticker: 'ETH', name: 'Ethereum' }, { ticker: 'ERG', name: 'Ergo' }],
  },
  {
    id: 'rtx-4080s-rig',
    model: 'RTX 4080S Mining Rig (8x)',
    manufacturer: 'Custom Build',
    type: 'GPU',
    algorithm: 'Ethash/KawPow',
    algorithmFull: 'Ethash / KawPow (ETH/RVN)',
    hashrate: 640,
    hashrateUnit: 'MH/s',
    power: 3200,
    powerUnit: 'W',
    efficiency: 5.0,
    efficiencyUnit: 'J/TH',
    cost: 9600,
    dailyProfit: 6.80,
    monthlyProfit: 204.00,
    releaseDate: '2024-02',
    specs: ['8x RTX 4080 Super', 'Multi-Algorithm', 'Open Frame'],
    dimensions: '600×300×400mm (Open Frame)',
    noise: '60dB',
    voltage: '240V',
    weight: '20.0kg',
    coins: [{ ticker: 'ETH', name: 'Ethereum' }, { ticker: 'RVN', name: 'Ravencoin' }],
  },
  {
    id: 'antminer-ks5',
    model: 'Antminer KS5 Pro',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (Kaspa)',
    hashrate: 21,
    hashrateUnit: 'TH/s',
    power: 3150,
    powerUnit: 'W',
    efficiency: 150,
    efficiencyUnit: 'J/TH',
    cost: 8500,
    dailyProfit: 22.30,
    monthlyProfit: 669.00,
    releaseDate: '2023-09',
    specs: ['Kaspa Mining', 'kHeavyHash', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16.5kg',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'ice-river-ks3',
    model: 'IceRiver KS3 Ultra',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (Kaspa)',
    hashrate: 12,
    hashrateUnit: 'TH/s',
    power: 3400,
    powerUnit: 'W',
    efficiency: 283,
    efficiencyUnit: 'J/TH',
    cost: 4200,
    dailyProfit: 14.60,
    monthlyProfit: 438.00,
    releaseDate: '2023-08',
    specs: ['Kaspa Mining', 'kHeavyHash', 'Air Cooled'],
    dimensions: '400×180×280mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14.8kg',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'goldshell-boxx400',
    model: 'GoldShell BOXx400',
    manufacturer: 'GoldShell',
    type: 'ASIC',
    algorithm: 'Blake3',
    algorithmFull: 'Blake3 (ALPH/IRON)',
    hashrate: 400,
    hashrateUnit: 'GH/s',
    power: 1800,
    powerUnit: 'W',
    efficiency: 4.5,
    efficiencyUnit: 'J/GH',
    cost: 1200,
    dailyProfit: 3.20,
    monthlyProfit: 96.00,
    releaseDate: '2024-05',
    specs: ['Blake3 Algorithm', 'Desktop Form', 'Quiet Operation'],
    dimensions: '200×150×85mm',
    noise: '45dB',
    voltage: '110-240V',
    weight: '3.2kg',
    coins: [{ ticker: 'ALPH', name: 'Alephium' }, { ticker: 'IRON', name: 'Iron Fish' }],
  },
  {
    id: 'antminer-z15-pro',
    model: 'Antminer Z15 Pro',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash (ZEC/ZEN)',
    hashrate: 420,
    hashrateUnit: 'KH/s',
    power: 1510,
    powerUnit: 'W',
    efficiency: 3.6,
    efficiencyUnit: 'J/TH',
    cost: 3200,
    dailyProfit: 6.75,
    monthlyProfit: 202.50,
    releaseDate: '2024-01',
    specs: ['Equihash Algorithm', 'ZEC Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14.2kg',
    coins: [{ ticker: 'ZEC', name: 'Zcash' }, { ticker: 'ZEN', name: 'Horizen' }],
  },
  {
    id: 'ice-river-alph',
    model: 'IceRiver ALPH Miner',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'Blake3',
    algorithmFull: 'Blake3 (Alephium)',
    hashrate: 360,
    hashrateUnit: 'GH/s',
    power: 1500,
    powerUnit: 'W',
    efficiency: 4.17,
    efficiencyUnit: 'J/GH',
    cost: 2800,
    dailyProfit: 5.50,
    monthlyProfit: 165.00,
    releaseDate: '2024-06',
    specs: ['Alephium Mining', 'Blake3', 'Low Power'],
    dimensions: '400×180×280mm',
    noise: '65dB',
    voltage: '220V',
    weight: '12.5kg',
    coins: [{ ticker: 'ALPH', name: 'Alephium' }],
  },
{
    id: 'antminer-z15-pro-840kh',
    model: 'Antminer Z15 Pro (840kh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash',
    hashrate: 840,
    hashrateUnit: 'KH/s',
    power: 2780,
    powerUnit: 'W',
    efficiency: 3309523809.52,
    efficiencyUnit: 'J/GH',
    cost: 3999,
    dailyProfit: 51.89,
    monthlyProfit: 1556.7,
    releaseDate: 'Jun 2023',
    specs: ['Equihash Algorithm', 'ZEC/ZEN Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '14200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-x9-1mh',
    model: 'Antminer X9 (1Mh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'RandomX',
    algorithmFull: 'RandomX (XMR)',
    hashrate: 1,
    hashrateUnit: 'MH/s',
    power: 2472,
    powerUnit: 'W',
    efficiency: 2472000000,
    efficiencyUnit: 'J/GH',
    cost: 5360,
    dailyProfit: 30.15,
    monthlyProfit: 904.5,
    releaseDate: 'Jul 2026',
    specs: ['RandomX Algorithm', 'Monero Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '14500g',
    coins: [{ ticker: 'XMR', name: 'Monero' }],
  },
  {
    id: 'antminer-z15-420kh',
    model: 'Antminer Z15 (420kh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash',
    hashrate: 420,
    hashrateUnit: 'KH/s',
    power: 1510,
    powerUnit: 'W',
    efficiency: 3595238095.24,
    efficiencyUnit: 'J/GH',
    cost: 770,
    dailyProfit: 25.66,
    monthlyProfit: 769.8,
    releaseDate: 'Jun 2020',
    specs: ['Equihash Algorithm', 'ZEC/ZEN Mining'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '14000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'inibox-pro-2-4gh',
    model: 'Matches INIBOX Pro (2.4Gh)',
    manufacturer: 'Pinecone',
    type: 'ASIC',
    algorithm: 'VersaHash',
    algorithmFull: 'VersaHash (INI)',
    hashrate: 2.4,
    hashrateUnit: 'GH/s',
    power: 1280,
    powerUnit: 'W',
    efficiency: 533333.33,
    efficiencyUnit: 'J/GH',
    cost: 7799,
    dailyProfit: 15.76,
    monthlyProfit: 472.8,
    releaseDate: 'Mar 2026',
    specs: ['VersaHash Algorithm', 'INI Mining', 'Home Miner'],
    dimensions: '380×160×260mm',
    noise: '55dB',
    voltage: '220V',
    weight: '11500g',
    coins: [{ ticker: 'INI', name: 'InitVerse' }],
  },
  {
    id: 'iceriver-aleo-ae3-2gh',
    model: 'IceRiver ALEO AE3 (2Gh)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'zkSNARK',
    algorithmFull: 'zkSNARK (ALEO)',
    hashrate: 2,
    hashrateUnit: 'GH/s',
    power: 3400,
    powerUnit: 'W',
    efficiency: 1700000,
    efficiencyUnit: 'J/GH',
    cost: 5880,
    dailyProfit: 15.53,
    monthlyProfit: 465.9,
    releaseDate: 'Nov 2025',
    specs: ['zkSNARK Algorithm', 'Aleo Mining', 'Air Cooled'],
    dimensions: '400×180×280mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14800g',
    coins: [{ ticker: 'ALEO', name: 'Aleo' }],
  },
  {
    id: 'antminer-s23-hyd-3u-1-16ph',
    model: 'Antminer S23 Hyd 3U (1.16Ph)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.16,
    hashrateUnit: 'PH/s',
    power: 11020,
    powerUnit: 'W',
    efficiency: 9.5,
    efficiencyUnit: 'J/TH',
    cost: 7757,
    dailyProfit: 15.23,
    monthlyProfit: 456.9,
    releaseDate: 'Jan 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling', '3U Form Factor'],
    dimensions: '535×460×180mm',
    noise: '80dB',
    voltage: '220V',
    weight: '25000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'sealminer-a4-ultra-hydro-886th',
    model: 'SealMiner A4 Ultra Hydro (886Th)',
    manufacturer: 'Bitdeer',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 886,
    hashrateUnit: 'TH/s',
    power: 8372,
    powerUnit: 'W',
    efficiency: 9.45,
    efficiencyUnit: 'J/TH',
    cost: 9980,
    dailyProfit: 11.74,
    monthlyProfit: 352.2,
    releaseDate: 'May 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling'],
    dimensions: '450×220×300mm',
    noise: '75dB',
    voltage: '220V',
    weight: '18500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-s23e-hyd-2u-865th',
    model: 'Antminer S23e Hyd 2U (865Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 865,
    hashrateUnit: 'TH/s',
    power: 8650,
    powerUnit: 'W',
    efficiency: 10,
    efficiencyUnit: 'J/TH',
    cost: 11699,
    dailyProfit: 10.32,
    monthlyProfit: 309.6,
    releaseDate: 'Apr 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling', '2U Form Factor'],
    dimensions: '535×460×180mm',
    noise: '80dB',
    voltage: '220V',
    weight: '24000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-s23-hyd-580th',
    model: 'Antminer S23 Hyd (580Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 580,
    hashrateUnit: 'TH/s',
    power: 5510,
    powerUnit: 'W',
    efficiency: 9.5,
    efficiencyUnit: 'J/TH',
    cost: 12949,
    dailyProfit: 7.62,
    monthlyProfit: 228.6,
    releaseDate: 'Jan 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling'],
    dimensions: '535×460×180mm',
    noise: '80dB',
    voltage: '220V',
    weight: '23000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'jasminer-x44-p-23-4gh',
    model: 'Jasminer X44-P (23.4Gh)',
    manufacturer: 'Jasminer',
    type: 'ASIC',
    algorithm: 'EtHash',
    algorithmFull: 'EtHash (ETC)',
    hashrate: 23.4,
    hashrateUnit: 'GH/s',
    power: 2550,
    powerUnit: 'W',
    efficiency: 108974.36,
    efficiencyUnit: 'J/GH',
    cost: 11300,
    dailyProfit: 6.96,
    monthlyProfit: 208.8,
    releaseDate: 'Jun 2025',
    specs: ['EtHash Algorithm', 'ETC Mining', 'Air Cooled'],
    dimensions: '400×180×280mm',
    noise: '65dB',
    voltage: '220V',
    weight: '12800g',
    coins: [{ ticker: 'ETC', name: 'Ethereum Classic' }],
  },
  {
    id: 'sealminer-a4-pro-hydro-680th',
    model: 'SealMiner A4 Pro Hydro (680Th)',
    manufacturer: 'Bitdeer',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 680,
    hashrateUnit: 'TH/s',
    power: 7412,
    powerUnit: 'W',
    efficiency: 10.9,
    efficiencyUnit: 'J/TH',
    cost: 8666,
    dailyProfit: 6.64,
    monthlyProfit: 199.2,
    releaseDate: 'May 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling'],
    dimensions: '450×220×300mm',
    noise: '75dB',
    voltage: '220V',
    weight: '17500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-l11-hyd-2u-35gh',
    model: 'Antminer L11 Hyd 2U (35Gh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 35,
    hashrateUnit: 'GH/s',
    power: 5775,
    powerUnit: 'W',
    efficiency: 165000,
    efficiencyUnit: 'J/GH',
    cost: 9000,
    dailyProfit: 6.36,
    monthlyProfit: 190.8,
    releaseDate: 'Dec 2025',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Hydro Cooling', '2U Form'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-l11-hyd-6u-33gh',
    model: 'Antminer L11 Hyd 6U (33Gh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 33,
    hashrateUnit: 'GH/s',
    power: 5676,
    powerUnit: 'W',
    efficiency: 172000,
    efficiencyUnit: 'J/GH',
    cost: 9627,
    dailyProfit: 5.44,
    monthlyProfit: 163.2,
    releaseDate: 'Dec 2025',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Hydro Cooling', '6U Form'],
    dimensions: '535×460×180mm',
    noise: '78dB',
    voltage: '220V',
    weight: '22000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'sealminer-dl1-air-25gh',
    model: 'SealMiner DL1 Air (25Gh)',
    manufacturer: 'Bitdeer',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 25,
    hashrateUnit: 'GH/s',
    power: 3725,
    powerUnit: 'W',
    efficiency: 149000,
    efficiencyUnit: 'J/GH',
    cost: 7298,
    dailyProfit: 5.5,
    monthlyProfit: 165,
    releaseDate: 'May 2026',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'matches-inibox-850mh',
    model: 'Matches INIBOX (850Mh)',
    manufacturer: 'Pinecone',
    type: 'ASIC',
    algorithm: 'VersaHash',
    algorithmFull: 'VersaHash (INI)',
    hashrate: 850,
    hashrateUnit: 'MH/s',
    power: 500,
    powerUnit: 'W',
    efficiency: 588235.29,
    efficiencyUnit: 'J/GH',
    cost: 4065,
    dailyProfit: 5.47,
    monthlyProfit: 164.1,
    releaseDate: 'Jul 2025',
    specs: ['VersaHash Algorithm', 'INI Mining', 'Home Miner', 'Quiet Operation'],
    dimensions: '260×150×220mm',
    noise: '45dB',
    voltage: '220V',
    weight: '5200g',
    coins: [{ ticker: 'INI', name: 'InitVerse' }],
  },
  {
    id: 'iceriver-aleo-ae2-720mh',
    model: 'IceRiver ALEO AE2 (720Mh)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'zkSNARK',
    algorithmFull: 'zkSNARK (ALEO)',
    hashrate: 720,
    hashrateUnit: 'MH/s',
    power: 1300,
    powerUnit: 'W',
    efficiency: 1805555.56,
    efficiencyUnit: 'J/GH',
    cost: 2538,
    dailyProfit: 5.41,
    monthlyProfit: 162.3,
    releaseDate: 'Jul 2025',
    specs: ['zkSNARK Algorithm', 'Aleo Mining', 'Home Miner'],
    dimensions: '380×160×260mm',
    noise: '60dB',
    voltage: '220V',
    weight: '10500g',
    coins: [{ ticker: 'ALEO', name: 'Aleo' }],
  },
  {
    id: 'antminer-s21-xp-plus-hyd-500th',
    model: 'Antminer S21 XP+ Hyd (500Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 500,
    hashrateUnit: 'TH/s',
    power: 5500,
    powerUnit: 'W',
    efficiency: 11,
    efficiencyUnit: 'J/TH',
    cost: 9500,
    dailyProfit: 4.77,
    monthlyProfit: 143.1,
    releaseDate: 'Jul 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling'],
    dimensions: '450×220×300mm',
    noise: '78dB',
    voltage: '220V',
    weight: '19500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-l9-17gh',
    model: 'Antminer L9 (17Gh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 17,
    hashrateUnit: 'GH/s',
    power: 3570,
    powerUnit: 'W',
    efficiency: 210000,
    efficiencyUnit: 'J/GH',
    cost: 6800,
    dailyProfit: 4.35,
    monthlyProfit: 130.5,
    releaseDate: 'Jun 2024',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '70dB',
    voltage: '220V',
    weight: '16000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-ks7-40th',
    model: 'Antminer KS7 (40Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (KAS)',
    hashrate: 40,
    hashrateUnit: 'TH/s',
    power: 3080,
    powerUnit: 'W',
    efficiency: 77,
    efficiencyUnit: 'J/TH',
    cost: 7900,
    dailyProfit: 4.1,
    monthlyProfit: 123,
    releaseDate: 'Dec 2025',
    specs: ['kHeavyHash Algorithm', 'Kaspa Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16500g',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'whatsminer-m60-172th',
    model: 'Whatsminer M60 (172Th)',
    manufacturer: 'MicroBT',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 172,
    hashrateUnit: 'TH/s',
    power: 3422,
    powerUnit: 'W',
    efficiency: 19.9,
    efficiencyUnit: 'J/TH',
    cost: 4200,
    dailyProfit: 3.85,
    monthlyProfit: 115.5,
    releaseDate: 'Jan 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Air Cooled'],
    dimensions: '430×215×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-s21-pro-234th',
    model: 'Antminer S21 Pro (234Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256',
    hashrate: 234,
    hashrateUnit: 'TH/s',
    power: 3510,
    powerUnit: 'W',
    efficiency: 15,
    efficiencyUnit: 'J/TH',
    cost: 5500,
    dailyProfit: 5.2,
    monthlyProfit: 156,
    releaseDate: 'Mar 2024',
    specs: ['2nm Chip', 'SHA-256', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-s21-200th',
    model: 'Antminer S21 (200Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256',
    hashrate: 200,
    hashrateUnit: 'TH/s',
    power: 3500,
    powerUnit: 'W',
    efficiency: 17.5,
    efficiencyUnit: 'J/TH',
    cost: 4200,
    dailyProfit: 4.45,
    monthlyProfit: 133.5,
    releaseDate: 'Dec 2023',
    specs: ['7nm Chip', 'SHA-256', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '15800g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'whatsminer-m50s-186th',
    model: 'Whatsminer M50S (186Th)',
    manufacturer: 'MicroBT',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256',
    hashrate: 186,
    hashrateUnit: 'TH/s',
    power: 3348,
    powerUnit: 'W',
    efficiency: 18,
    efficiencyUnit: 'J/TH',
    cost: 3800,
    dailyProfit: 4.15,
    monthlyProfit: 124.5,
    releaseDate: 'Jan 2024',
    specs: ['6nm Chip', 'SHA-256', 'Air Cooled'],
    dimensions: '430×215×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '14900g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-ks5-pro-21th',
    model: 'Antminer KS5 Pro (21Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (KAS)',
    hashrate: 21,
    hashrateUnit: 'TH/s',
    power: 3150,
    powerUnit: 'W',
    efficiency: 150,
    efficiencyUnit: 'J/TH',
    cost: 8500,
    dailyProfit: 22.3,
    monthlyProfit: 669,
    releaseDate: 'Sep 2023',
    specs: ['kHeavyHash Algorithm', 'Kaspa Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16500g',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'iceriver-ks3-ultra-12th',
    model: 'IceRiver KS3 Ultra (12Th)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (KAS)',
    hashrate: 12,
    hashrateUnit: 'TH/s',
    power: 3400,
    powerUnit: 'W',
    efficiency: 283.33,
    efficiencyUnit: 'J/TH',
    cost: 4200,
    dailyProfit: 14.6,
    monthlyProfit: 438,
    releaseDate: 'Aug 2023',
    specs: ['kHeavyHash Algorithm', 'Kaspa Mining', 'Air Cooled'],
    dimensions: '400×180×280mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14800g',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'goldshell-xt-box-580g',
    model: 'GoldShell XT-BOX (580G)',
    manufacturer: 'GoldShell',
    type: 'ASIC',
    algorithm: 'SHA3x',
    algorithmFull: 'SHA3x (XTM)',
    hashrate: 580,
    hashrateUnit: 'GH/s',
    power: 400,
    powerUnit: 'W',
    efficiency: 689.66,
    efficiencyUnit: 'J/GH',
    cost: 1890,
    dailyProfit: 3.2,
    monthlyProfit: 96,
    releaseDate: 'Jan 2026',
    specs: ['SHA3x Algorithm', 'XTM Mining', 'Desktop Form', 'Quiet'],
    dimensions: '200×150×85mm',
    noise: '45dB',
    voltage: '220V',
    weight: '3200g',
    coins: [{ ticker: 'XTM', name: 'Torrent' }],
  },
  {
    id: 'antminer-d9-1-77th',
    model: 'Antminer D9 (1.77Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'X11',
    algorithmFull: 'X11 (DASH)',
    hashrate: 1.77,
    hashrateUnit: 'TH/s',
    power: 2580,
    powerUnit: 'W',
    efficiency: 1457.63,
    efficiencyUnit: 'J/TH',
    cost: 3500,
    dailyProfit: 2.85,
    monthlyProfit: 85.5,
    releaseDate: 'Mar 2025',
    specs: ['X11 Algorithm', 'DASH Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15500g',
    coins: [{ ticker: 'DASH', name: 'Dash' }],
  },
  {
    id: 'volcminer-d1-hydro-33gh',
    model: 'VolcMiner D1 Hydro (33Gh)',
    manufacturer: 'VolcMiner',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 33,
    hashrateUnit: 'GH/s',
    power: 7600,
    powerUnit: 'W',
    efficiency: 230303.03,
    efficiencyUnit: 'J/GH',
    cost: 10500,
    dailyProfit: 7.8,
    monthlyProfit: 234,
    releaseDate: 'Mar 2026',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Hydro Cooling'],
    dimensions: '535×460×180mm',
    noise: '80dB',
    voltage: '220V',
    weight: '26000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'elphapex-dg2-plus',
    model: 'ElphaPex DG2+ (15Gh)',
    manufacturer: 'ElphaPex',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 15,
    hashrateUnit: 'GH/s',
    power: 2800,
    powerUnit: 'W',
    efficiency: 186666.67,
    efficiencyUnit: 'J/GH',
    cost: 5500,
    dailyProfit: 3.95,
    monthlyProfit: 118.5,
    releaseDate: 'Feb 2025',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Air Cooled'],
    dimensions: '410×180×270mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'canaan-avalon-a1566ha-2u',
    model: 'Canaan Avalon A1566HA 2U (480Th)',
    manufacturer: 'Canaan',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 480,
    hashrateUnit: 'TH/s',
    power: 8064,
    powerUnit: 'W',
    efficiency: 16.8,
    efficiencyUnit: 'J/TH',
    cost: 8200,
    dailyProfit: 8.9,
    monthlyProfit: 267,
    releaseDate: 'Mar 2026',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', '2U Form Factor', 'Air Cooled'],
    dimensions: '535×460×180mm',
    noise: '78dB',
    voltage: '220V',
    weight: '22000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'canaan-avalon-q-90th',
    model: 'Canaan Avalon Q (90Th)',
    manufacturer: 'Canaan',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 90,
    hashrateUnit: 'TH/s',
    power: 1674,
    powerUnit: 'W',
    efficiency: 18.6,
    efficiencyUnit: 'J/TH',
    cost: 2800,
    dailyProfit: 2.1,
    monthlyProfit: 63,
    releaseDate: 'Jan 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Home Miner', 'Low Noise'],
    dimensions: '350×150×240mm',
    noise: '55dB',
    voltage: '220V',
    weight: '8500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'canaan-avalon-mini-3-37th',
    model: 'Canaan Avalon Mini 3 (37.5Th)',
    manufacturer: 'Canaan',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 37.5,
    hashrateUnit: 'TH/s',
    power: 800,
    powerUnit: 'W',
    efficiency: 21.33,
    efficiencyUnit: 'J/TH',
    cost: 1500,
    dailyProfit: 0.85,
    monthlyProfit: 25.5,
    releaseDate: 'Sep 2024',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'No Noise', 'Home Miner'],
    dimensions: '280×140×200mm',
    noise: '40dB',
    voltage: '220V',
    weight: '4500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'iceriver-ks0-100gh',
    model: 'IceRiver KS0 (100Gh)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (KAS)',
    hashrate: 100,
    hashrateUnit: 'GH/s',
    power: 65,
    powerUnit: 'W',
    efficiency: 650,
    efficiencyUnit: 'J/GH',
    cost: 300,
    dailyProfit: 0.35,
    monthlyProfit: 10.5,
    releaseDate: 'Sep 2023',
    specs: ['kHeavyHash Algorithm', 'Kaspa Mining', 'Ultra Low Power', 'Desktop'],
    dimensions: '180×120×80mm',
    noise: '40dB',
    voltage: '220V',
    weight: '2500g',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'bitaxe-gamma-601-1-2th',
    model: 'Bitaxe Gamma 601 (1.2Th)',
    manufacturer: 'Bitaxe',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.2,
    hashrateUnit: 'TH/s',
    power: 17,
    powerUnit: 'W',
    efficiency: 14.17,
    efficiencyUnit: 'J/TH',
    cost: 90,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Aug 2024',
    specs: ['SHA-256 Algorithm', 'SOLO BTC Mining', 'Ultra Compact', 'USB Powered'],
    dimensions: '60×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '300g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'nerdminer-nerdqaxe-2-5th',
    model: 'NerdMiner NerdQaxe+ (2.5Th)',
    manufacturer: 'NerdMiner',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 2.5,
    hashrateUnit: 'TH/s',
    power: 50,
    powerUnit: 'W',
    efficiency: 20,
    efficiencyUnit: 'J/TH',
    cost: 489,
    dailyProfit: 0.02,
    monthlyProfit: 0.6,
    releaseDate: 'Mar 2025',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Compact Design'],
    dimensions: '80×50×30mm',
    noise: '40dB',
    voltage: '220V',
    weight: '500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'lucky-miner-lv07-1th',
    model: 'Lucky Miner LV07 (1Th)',
    manufacturer: 'Lucky Miner',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1,
    hashrateUnit: 'TH/s',
    power: 25,
    powerUnit: 'W',
    efficiency: 25,
    efficiencyUnit: 'J/TH',
    cost: 88,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Jun 2024',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Low Cost Entry'],
    dimensions: '70×45×25mm',
    noise: '38dB',
    voltage: '220V',
    weight: '400g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'nerdminer-s19-1th',
    model: 'NerdMiner S19 (1Th)',
    manufacturer: 'NerdMiner',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1,
    hashrateUnit: 'TH/s',
    power: 20,
    powerUnit: 'W',
    efficiency: 20,
    efficiencyUnit: 'J/TH',
    cost: 60,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Jan 2024',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Entry Level'],
    dimensions: '65×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '350g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'jingle-miner-btc-solo-lite-1-2th',
    model: 'Jingle Miner BTC Solo Lite (1.2Th)',
    manufacturer: 'Jingle Miner',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.2,
    hashrateUnit: 'TH/s',
    power: 23,
    powerUnit: 'W',
    efficiency: 19.17,
    efficiencyUnit: 'J/TH',
    cost: 119,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Sep 2025',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'USB Powered'],
    dimensions: '60×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '300g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-z11-135kh',
    model: 'Antminer Z11 (135kh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash',
    hashrate: 135,
    hashrateUnit: 'KH/s',
    power: 1418,
    powerUnit: 'W',
    efficiency: 10503703703.7,
    efficiencyUnit: 'J/GH',
    cost: 999,
    dailyProfit: 6.01,
    monthlyProfit: 180.3,
    releaseDate: 'Apr 2019',
    specs: ['Equihash Algorithm', 'ZEC Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '70dB',
    voltage: '220V',
    weight: '13800g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'innosilicon-a9-plus-zmaster-140kh',
    model: 'Innosilicon A9++ ZMaster (140kh)',
    manufacturer: 'Innosilicon',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash',
    hashrate: 140,
    hashrateUnit: 'KH/s',
    power: 1550,
    powerUnit: 'W',
    efficiency: 11071428571.43,
    efficiencyUnit: 'J/GH',
    cost: 1200,
    dailyProfit: 6.04,
    monthlyProfit: 181.2,
    releaseDate: 'May 2019',
    specs: ['Equihash Algorithm', 'ZEC Mining', 'Air Cooled'],
    dimensions: '420×190×280mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'innosilicon-a9-zmaster-120kh',
    model: 'Innosilicon A9+ ZMaster (120kh)',
    manufacturer: 'Innosilicon',
    type: 'ASIC',
    algorithm: 'Equihash',
    algorithmFull: 'Equihash',
    hashrate: 120,
    hashrateUnit: 'KH/s',
    power: 1550,
    powerUnit: 'W',
    efficiency: 12916666666.67,
    efficiencyUnit: 'J/GH',
    cost: 1000,
    dailyProfit: 4.65,
    monthlyProfit: 139.5,
    releaseDate: 'Jan 2019',
    specs: ['Equihash Algorithm', 'ZEC Mining', 'Air Cooled'],
    dimensions: '420×190×280mm',
    noise: '70dB',
    voltage: '220V',
    weight: '14000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'ice-river-alph-360gh',
    model: 'IceRiver ALPH (360Gh)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'Blake3',
    algorithmFull: 'Blake3 (ALPH)',
    hashrate: 360,
    hashrateUnit: 'GH/s',
    power: 1500,
    powerUnit: 'W',
    efficiency: 4166.67,
    efficiencyUnit: 'J/GH',
    cost: 2800,
    dailyProfit: 5.5,
    monthlyProfit: 165,
    releaseDate: 'Jun 2024',
    specs: ['Blake3 Algorithm', 'Alephium Mining', 'Low Power'],
    dimensions: '400×180×280mm',
    noise: '65dB',
    voltage: '220V',
    weight: '12500g',
    coins: [{ ticker: 'ALPH', name: 'Alephium' }],
  },
  {
    id: 'jasminer-x16-q-pro-2-05gh',
    model: 'Jasminer X16-Q Pro (2.05Gh)',
    manufacturer: 'Jasminer',
    type: 'ASIC',
    algorithm: 'EtHash',
    algorithmFull: 'EtHash (ETC)',
    hashrate: 2.05,
    hashrateUnit: 'GH/s',
    power: 520,
    powerUnit: 'W',
    efficiency: 253658.54,
    efficiencyUnit: 'J/GH',
    cost: 2400,
    dailyProfit: 1.65,
    monthlyProfit: 49.5,
    releaseDate: 'Jan 2025',
    specs: ['EtHash Algorithm', 'ETC Mining', 'Quiet Operation'],
    dimensions: '320×160×240mm',
    noise: '55dB',
    voltage: '220V',
    weight: '6800g',
    coins: [{ ticker: 'ETC', name: 'Ethereum Classic' }],
  },
  {
    id: 'bitdeer-sealminer-a2-226th',
    model: 'Bitdeer SealMiner A2 (226Th)',
    manufacturer: 'Bitdeer',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 226,
    hashrateUnit: 'TH/s',
    power: 3800,
    powerUnit: 'W',
    efficiency: 16.81,
    efficiencyUnit: 'J/TH',
    cost: 5200,
    dailyProfit: 4.8,
    monthlyProfit: 144,
    releaseDate: 'Jan 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15500g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitdeer-sealminer-a2-pro-air-255th',
    model: 'SealMiner A2 Pro Air (255Th)',
    manufacturer: 'Bitdeer',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 255,
    hashrateUnit: 'TH/s',
    power: 3790,
    powerUnit: 'W',
    efficiency: 14.86,
    efficiencyUnit: 'J/TH',
    cost: 5800,
    dailyProfit: 5.5,
    monthlyProfit: 165,
    releaseDate: 'Jan 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Air Cooled', 'High Efficiency'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15800g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-l11-pro-21gh',
    model: 'Antminer L11 Pro (21Gh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 21,
    hashrateUnit: 'GH/s',
    power: 3612,
    powerUnit: 'W',
    efficiency: 172000,
    efficiencyUnit: 'J/GH',
    cost: 7200,
    dailyProfit: 4.8,
    monthlyProfit: 144,
    releaseDate: 'Dec 2025',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Air Cooled', '0.172j/Mh'],
    dimensions: '430×195×290mm',
    noise: '73dB',
    voltage: '220V',
    weight: '16200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'iceriver-aleo-ae1-lite-300mh',
    model: 'IceRiver ALEO AE1 Lite (300Mh)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'zkSNARK',
    algorithmFull: 'zkSNARK (ALEO)',
    hashrate: 300,
    hashrateUnit: 'MH/s',
    power: 500,
    powerUnit: 'W',
    efficiency: 1666666.67,
    efficiencyUnit: 'J/GH',
    cost: 1200,
    dailyProfit: 2.8,
    monthlyProfit: 84,
    releaseDate: 'Sep 2025',
    specs: ['zkSNARK Algorithm', 'Aleo Mining', 'Low Power', 'Home Miner'],
    dimensions: '350×150×240mm',
    noise: '55dB',
    voltage: '220V',
    weight: '8500g',
    coins: [{ ticker: 'ALEO', name: 'Aleo' }],
  },
  {
    id: 'iceriver-kas-ks7-lite-4-2th',
    model: 'IceRiver KAS KS7 Lite (4.2Th)',
    manufacturer: 'IceRiver',
    type: 'ASIC',
    algorithm: 'kHeavyHash',
    algorithmFull: 'kHeavyHash (KAS)',
    hashrate: 4.2,
    hashrateUnit: 'TH/s',
    power: 500,
    powerUnit: 'W',
    efficiency: 119.05,
    efficiencyUnit: 'J/TH',
    cost: 2800,
    dailyProfit: 4.2,
    monthlyProfit: 126,
    releaseDate: 'Mar 2026',
    specs: ['kHeavyHash Algorithm', 'Kaspa Mining', 'Low Power', 'Home Miner'],
    dimensions: '320×160×240mm',
    noise: '55dB',
    voltage: '220V',
    weight: '7200g',
    coins: [{ ticker: 'KAS', name: 'Kaspa' }],
  },
  {
    id: 'bitaxe-touch-1-6th',
    model: 'Bitaxe Touch (1.6Th)',
    manufacturer: 'Bitaxe',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.6,
    hashrateUnit: 'TH/s',
    power: 22,
    powerUnit: 'W',
    efficiency: 13.75,
    efficiencyUnit: 'J/TH',
    cost: 346,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Dec 2024',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Touch Screen'],
    dimensions: '80×50×25mm',
    noise: '35dB',
    voltage: '220V',
    weight: '600g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitaxe-supra-401-600gh',
    model: 'Bitaxe Supra 401 (600Gh)',
    manufacturer: 'Bitaxe',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 600,
    hashrateUnit: 'GH/s',
    power: 14,
    powerUnit: 'W',
    efficiency: 23.33,
    efficiencyUnit: 'J/GH',
    cost: 110,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Jun 2024',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Ultra Efficient'],
    dimensions: '60×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '400g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitmain-antminer-s19-xp-hyd-293th',
    model: 'Antminer S19 XP+ Hyd (293Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 293,
    hashrateUnit: 'TH/s',
    power: 5567,
    powerUnit: 'W',
    efficiency: 19,
    efficiencyUnit: 'J/TH',
    cost: 7500,
    dailyProfit: 6.2,
    monthlyProfit: 186,
    releaseDate: 'Jun 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Hydro Cooling'],
    dimensions: '450×220×300mm',
    noise: '78dB',
    voltage: '220V',
    weight: '21000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'canaan-avalon-a15pro-218th',
    model: 'Canaan Avalon A15Pro (218Th)',
    manufacturer: 'Canaan',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 218,
    hashrateUnit: 'TH/s',
    power: 4000,
    powerUnit: 'W',
    efficiency: 18.35,
    efficiencyUnit: 'J/TH',
    cost: 4800,
    dailyProfit: 4.6,
    monthlyProfit: 138,
    releaseDate: 'Feb 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Air Cooled', 'A15 Series'],
    dimensions: '430×195×290mm',
    noise: '72dB',
    voltage: '220V',
    weight: '15200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'whatsminer-m66-280th',
    model: 'MicroBT Whatsminer M66 (280Th)',
    manufacturer: 'MicroBT',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 280,
    hashrateUnit: 'TH/s',
    power: 5040,
    powerUnit: 'W',
    efficiency: 18,
    efficiencyUnit: 'J/TH',
    cost: 6500,
    dailyProfit: 5.9,
    monthlyProfit: 177,
    releaseDate: 'Apr 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Oil Cooling', 'Immersion Ready'],
    dimensions: '450×220×300mm',
    noise: '75dB',
    voltage: '220V',
    weight: '18000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'antminer-s21-xp-270th',
    model: 'Antminer S21 XP (270Th)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 270,
    hashrateUnit: 'TH/s',
    power: 3645,
    powerUnit: 'W',
    efficiency: 13.5,
    efficiencyUnit: 'J/TH',
    cost: 7000,
    dailyProfit: 6.8,
    monthlyProfit: 204,
    releaseDate: 'Jan 2025',
    specs: ['SHA-256 Algorithm', 'Bitcoin Mining', 'Air Cooled', 'High Efficiency'],
    dimensions: '430×195×290mm',
    noise: '75dB',
    voltage: '220V',
    weight: '16200g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'plebsource-hammer-miner-scrypt-105mh',
    model: 'PlebSource Hammer Miner Scrypt (105Mh)',
    manufacturer: 'PlebSource',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 105,
    hashrateUnit: 'MH/s',
    power: 25,
    powerUnit: 'W',
    efficiency: 238095.24,
    efficiencyUnit: 'J/GH',
    cost: 150,
    dailyProfit: 0.02,
    monthlyProfit: 0.6,
    releaseDate: 'Jan 2026',
    specs: ['Scrypt Algorithm', 'Solo LTC Mining', 'USB Powered'],
    dimensions: '70×45×25mm',
    noise: '50dB',
    voltage: '220V',
    weight: '400g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'braiins-bmm100-1th',
    model: 'Braiins BMM100 (1Th)',
    manufacturer: 'Braiins',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1,
    hashrateUnit: 'TH/s',
    power: 40,
    powerUnit: 'W',
    efficiency: 40,
    efficiencyUnit: 'J/TH',
    cost: 200,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Jun 2024',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Open Source Firmware'],
    dimensions: '120×80×40mm',
    noise: '40dB',
    voltage: '220V',
    weight: '1300g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'digital-shovel-bluax-1-2th',
    model: 'Digital Shovel BluAx (1.2Th)',
    manufacturer: 'Digital Shovel',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.2,
    hashrateUnit: 'TH/s',
    power: 18,
    powerUnit: 'W',
    efficiency: 15,
    efficiencyUnit: 'J/TH',
    cost: 180,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Jul 2025',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Compact'],
    dimensions: '60×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '300g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitaxe-gamma-duo-650-1-63th',
    model: 'Bitaxe Gamma Duo 650 (1.63Th)',
    manufacturer: 'Bitaxe',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 1.63,
    hashrateUnit: 'TH/s',
    power: 26,
    powerUnit: 'W',
    efficiency: 15.95,
    efficiencyUnit: 'J/TH',
    cost: 250,
    dailyProfit: 0.01,
    monthlyProfit: 0.3,
    releaseDate: 'Feb 2026',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'Dual Hash Board'],
    dimensions: '60×40×20mm',
    noise: '35dB',
    voltage: '220V',
    weight: '300g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitaxe-gamma-turbo-2-4th',
    model: 'Bitaxe Gamma Turbo (2.4Th)',
    manufacturer: 'Bitaxe',
    type: 'ASIC',
    algorithm: 'SHA-256',
    algorithmFull: 'SHA-256 (BTC)',
    hashrate: 2.4,
    hashrateUnit: 'TH/s',
    power: 35,
    powerUnit: 'W',
    efficiency: 14.58,
    efficiencyUnit: 'J/TH',
    cost: 209,
    dailyProfit: 0.02,
    monthlyProfit: 0.6,
    releaseDate: 'Mar 2025',
    specs: ['SHA-256 Algorithm', 'Solo BTC Mining', 'High Hashrate'],
    dimensions: '70×45×25mm',
    noise: '35dB',
    voltage: '220V',
    weight: '400g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
  {
    id: 'bitmain-antminer-l11-20gh',
    model: 'Antminer L11 (20Gh)',
    manufacturer: 'Bitmain',
    type: 'ASIC',
    algorithm: 'Scrypt',
    algorithmFull: 'Scrypt',
    hashrate: 20,
    hashrateUnit: 'GH/s',
    power: 3680,
    powerUnit: 'W',
    efficiency: 184000,
    efficiencyUnit: 'J/GH',
    cost: 6200,
    dailyProfit: 4.2,
    monthlyProfit: 126,
    releaseDate: 'Dec 2025',
    specs: ['Scrypt Algorithm', 'LTC/DOGE Mining', 'Air Cooled'],
    dimensions: '430×195×290mm',
    noise: '73dB',
    voltage: '220V',
    weight: '16000g',
    coins: [{ ticker: 'BTC', name: 'Bitcoin' }],
  },
];

export function calculateProfitability(hashrate: number, powerW: number, elecCostPerKwh: number, grossDaily: number) {
  const powerCostDaily = (powerW / 1000) * 24 * elecCostPerKwh;
  const powerCostMonthly = powerCostDaily * 30;
  const powerCostYearly = powerCostDaily * 365;
  const grossMonthly = grossDaily * 30;
  const grossYearly = grossDaily * 365;
  const netDaily = grossDaily - powerCostDaily;
  const netMonthly = grossMonthly - powerCostMonthly;
  const netYearly = grossYearly - powerCostYearly;
  return { grossDaily, grossMonthly, grossYearly, powerCostDaily, powerCostMonthly, powerCostYearly, netDaily, netMonthly, netYearly };
}
