import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://bitcoinurdu.com';
  const now = new Date();

  const staticRoutes: { url: string; priority: number; changeFreq: 'daily' | 'weekly' | 'monthly' }[] = [
    { url: '/', priority: 1.0, changeFreq: 'daily' },
    { url: '/coins', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/categories', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/trending', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/gainers', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/losers', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/new', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/calendar', priority: 0.9, changeFreq: 'daily' },
    { url: '/coins/compare', priority: 0.8, changeFreq: 'weekly' },
    { url: '/coins/watchlist', priority: 0.8, changeFreq: 'weekly' },
    { url: '/coins/defi', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/memecoins', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/ai-tokens', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/gaming', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/rwa', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/stablecoins', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/launches', priority: 0.8, changeFreq: 'daily' },
    { url: '/coins/mining', priority: 0.8, changeFreq: 'daily' },
    { url: '/mining', priority: 0.9, changeFreq: 'daily' },
    { url: '/mining/miners/antminer-s21-200th', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/miners/antminer-z15-pro-840kh', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/asic', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/gpu', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/cpu', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/calculator', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/profitability', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/pools', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/firmware', priority: 0.7, changeFreq: 'weekly' },
    { url: '/mining/hosting', priority: 0.8, changeFreq: 'weekly' },
    { url: '/mining/guides', priority: 0.7, changeFreq: 'weekly' },
    { url: '/mining/news', priority: 0.7, changeFreq: 'weekly' },
    { url: '/airdrops', priority: 0.8, changeFreq: 'daily' },
    { url: '/airdrops/upcoming', priority: 0.8, changeFreq: 'daily' },
    { url: '/airdrops/confirmed', priority: 0.8, changeFreq: 'daily' },
    { url: '/airdrops/ended', priority: 0.7, changeFreq: 'daily' },
    { url: '/airdrops/retroactive', priority: 0.8, changeFreq: 'daily' },
    { url: '/airdrops/testnet', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets', priority: 0.9, changeFreq: 'daily' },
    { url: '/markets/heatmap', priority: 0.9, changeFreq: 'daily' },
    { url: '/markets/global', priority: 0.9, changeFreq: 'daily' },
    { url: '/markets/stocks', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets/forex', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets/commodities', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets/etfs', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets/bonds', priority: 0.8, changeFreq: 'daily' },
    { url: '/markets/indices', priority: 0.8, changeFreq: 'daily' },
    { url: '/news', priority: 0.7, changeFreq: 'daily' },
    { url: '/blog', priority: 0.7, changeFreq: 'daily' },
    { url: '/research', priority: 0.7, changeFreq: 'weekly' },
    { url: '/learn-bitcoin', priority: 0.7, changeFreq: 'weekly' },
    { url: '/learn', priority: 0.7, changeFreq: 'weekly' },
    { url: '/academy', priority: 0.7, changeFreq: 'weekly' },
    { url: '/glossary', priority: 0.7, changeFreq: 'monthly' },
    { url: '/analysis', priority: 0.7, changeFreq: 'daily' },
    { url: '/guides', priority: 0.7, changeFreq: 'weekly' },
    { url: '/tutorials', priority: 0.7, changeFreq: 'weekly' },
    { url: '/tools', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/gas-tracker', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/crypto-converter', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/dca-calculator', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/compound-interest', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/roi-calculator', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/rug-checker', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/whale-tracker', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/wallet-tracker', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/portfolio-tracker', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/fear-greed', priority: 0.8, changeFreq: 'daily' },
    { url: '/tools/bridge-finder', priority: 0.8, changeFreq: 'weekly' },
    { url: '/tools/token-approvals', priority: 0.8, changeFreq: 'weekly' },
    { url: '/exchanges', priority: 0.9, changeFreq: 'daily' },
    { url: '/exchanges/binance', priority: 0.9, changeFreq: 'daily' },
    { url: '/exchanges/cex', priority: 0.9, changeFreq: 'weekly' },
    { url: '/exchanges/dex', priority: 0.9, changeFreq: 'weekly' },
    { url: '/token-unlocks', priority: 0.8, changeFreq: 'daily' },
    { url: '/portfolio', priority: 0.8, changeFreq: 'daily' },
    { url: '/alerts', priority: 0.8, changeFreq: 'daily' },
    { url: '/converter', priority: 0.8, changeFreq: 'daily' },
    { url: '/search', priority: 0.8, changeFreq: 'daily' },
    { url: '/jobs', priority: 0.8, changeFreq: 'daily' },
    { url: '/about', priority: 0.6, changeFreq: 'monthly' },
    { url: '/contact', priority: 0.6, changeFreq: 'monthly' },
    { url: '/privacy-policy', priority: 0.5, changeFreq: 'monthly' },
    { url: '/terms', priority: 0.5, changeFreq: 'monthly' },
    { url: '/disclaimer', priority: 0.5, changeFreq: 'monthly' },
    { url: '/advertise', priority: 0.6, changeFreq: 'monthly' },
    { url: '/support-us', priority: 0.6, changeFreq: 'monthly' },
    { url: '/donate', priority: 0.6, changeFreq: 'monthly' },
    { url: '/login', priority: 0.5, changeFreq: 'monthly' },
    { url: '/register', priority: 0.5, changeFreq: 'monthly' },
    { url: '/forgot-password', priority: 0.5, changeFreq: 'monthly' },
    { url: '/profile', priority: 0.5, changeFreq: 'monthly' },
    { url: '/settings', priority: 0.5, changeFreq: 'monthly' },
    { url: '/careers', priority: 0.6, changeFreq: 'weekly' },
    { url: '/cookies', priority: 0.5, changeFreq: 'monthly' },
    { url: '/dmca', priority: 0.5, changeFreq: 'monthly' },
    { url: '/roadmap', priority: 0.6, changeFreq: 'monthly' },
    { url: '/partners', priority: 0.6, changeFreq: 'monthly' },
    { url: '/api-docs', priority: 0.6, changeFreq: 'monthly' },
    { url: '/status', priority: 0.7, changeFreq: 'daily' },
    { url: '/press-release', priority: 0.7, changeFreq: 'weekly' },
    { url: '/auth', priority: 0.5, changeFreq: 'monthly' },
  ];

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route.url}`,
    lastModified: now,
    changeFrequency: route.changeFreq,
    priority: route.priority,
  }));
}
